name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout to repository
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version from Git tags
      id: version
      run: |
        # Get the latest tag, increment it, or start with 1.0.0
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
        IFS='.' read -r major minor patch <<< "${latest_tag}"
        patch=$((patch + 1))
        new_tag="$major.$minor.$patch"
        echo "version=$new_tag" >> "$GITHUB_ENV"

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        
    - name: Create Git Tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ env.version }}
        git push origin ${{ env.version }}
