name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
      
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version from Git tags
      id: version
      run: |
        # Get the latest tag, increment it, or start with 1.0.0
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
        IFS='.' read -r major minor patch <<< "${latest_tag}"
        patch=$((patch + 1))
        new_tag="$major.$minor.$patch"
        echo "version=$new_tag"
        echo "::set-output name=version::$new_tag"

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

    - name: Create Git Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        git config user.name "gh_actions"
        git config user.email "gh_actions@users.noreply.github.com"
        git tag ${{ steps.version.outputs.version }}
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$REPO_NAME.git
        git push origin ${{ steps.version.outputs.version }}
